# Board name to build the app for.
board := "stm32u5a9j_dk"

# The chip to flash the board.
chip := "STM32U5A9NJ"

# The output directory.
output := "build"

# Print this message.
help:
    @just --list

# Build the app for the given board.
build:
    @west build -b {{board}} -d {{output}} app

# Flash the app to the given board.
flash: build
    @probe-rs download --chip {{chip}} --verify {{output}}/zephyr/zephyr.elf

# Clean the output directory (wipe all build data).
mrproper:
    @rm -rf {{output}}
